spring.application.name=walkie
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# path
server.servlet.context-path=/api/v1

spring.config.import=optional:classpath:application-key.properties

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${url}
spring.datasource.username=${id}
spring.datasource.password=${password}

# file
spring.web.resources.static-locations=classpath:/static/,file:files/
