spring.application.name=walkie
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# path
server.servlet.context-path=/api/v1

spring.config.import=optional:classpath:application-key.properties

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${url}
spring.datasource.username=${id}
spring.datasource.password=${password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.batch.job.enabled=false

# file
spring.web.resources.static-locations=classpath:/static/,file:files/

# kakao authentication
kakao.client_id=${REST_API_KEY}
kakao.redirect_uri=http://localhost:8080/api/v1/callback

# JWT
jwt.key=${JWT_KEY}

# Swagger UI ??
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=list
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.defaultModelsExpandDepth=-1

# ???? ??
server.tomcat.connection-timeout=10s

# ?? ?? ??
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB