spring.application.name=walkie
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.config.import=optional:classpath:application-key.properties

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${url}
spring.datasource.username=${id}
spring.datasource.password=${password}